const SET_QUESTIONS_NUMBER = 'stats/session/SET_QUESTIONS_NUMBER';
const SET_DIFFICULTY = 'stats/user/SET_DIFFICULTY';
const SET_QUESTIONS = 'stats/session/SET_QUESTIONS';
const UPDATE_QUESTION = 'stats/session/UPDATE_QUESTION';
const SET_TIME_ELAPSED = 'stats/session/SET_TIME_ELAPSED';
const SET_AVERAGE_SCORE = 'stats/session/SET_AVERAGE_SCORE';
const RESET_SESSION = 'stats/session/RESET_SESSION';

export {
  SET_QUESTIONS_NUMBER,
  SET_DIFFICULTY,
  SET_QUESTIONS,
  UPDATE_QUESTION,
  SET_TIME_ELAPSED,
  SET_AVERAGE_SCORE,
  RESET_SESSION,
};